// Code generated by qtc from "bioEdit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import "strings"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type BioEditPage struct {
	BasePage
	FieldName      string
	InitialContent string
}

func (p *BioEditPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<div>

    <h2>Editing `)
	qw422016.E().S(strings.ToLower(string(p.FieldName[0])) + p.FieldName[1:len(p.FieldName)])
	qw422016.N().S(`</h2>

    <p class="text-secondary"><i>Leave this box empty and save to delete the entry.</i></p>

    <form action="" method="POST">
        <div class="input-group">
            <textarea class="form-control" name="new" rows="20" aria-label="Edit content" id="editBox"></textarea>
            <input type="submit" class="input-group-text btn btn-primary d-none d-md-block" value="Save">
        </div>
        <input type="submit" class="input-group-text btn btn-primary d-md-none" style="width: 100%;" value="Save">
    </form>

    <script>
        const content = "`)
	qw422016.N().J(p.InitialContent)
	qw422016.N().S(`";
        document.getElementById("editBox").value = content;
    </script>

</div>
`)
}

func (p *BioEditPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *BioEditPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
