// Code generated by qtc from "bioSearch.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import "github.com/codemicro/lgballtDiscordBot/internal/db"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type BioSearchPage struct {
	BasePage
	ShowSearchResults bool
	SearchResults     []db.UserBio
}

func (p *BioSearchPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<div>

    <form action="">
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="q" placeholder="Search query (user ID/system ID/system member ID)" aria-label="Search query">
            <input type="submit" class="input-group-text btn btn-primary" value="Search">
        </div>
    </form>

    `)
	if p.ShowSearchResults {
		qw422016.N().S(`

        <p>Found `)
		qw422016.N().D(len(p.SearchResults))
		qw422016.N().S(` results</p>

        `)
		for _, result := range p.SearchResults {
			qw422016.N().S(`
            <div class="search-result">
                <a href="`)
			qw422016.N().S(ViewURL(result))
			qw422016.N().S(`">User ID: `)
			qw422016.E().S(result.UserId)
			qw422016.N().S(`
                    `)
			if result.SysMemberID != "" {
				qw422016.N().S(`
                        - System member ID: `)
				qw422016.E().S(result.SysMemberID)
				qw422016.N().S(` - System ID: `)
				qw422016.E().S(result.SystemID)
				qw422016.N().S(`
                    `)
			}
			qw422016.N().S(`
                </a>
            </div>

        `)
		}
		qw422016.N().S(`

    `)
	}
	qw422016.N().S(`

</div>
`)
}

func (p *BioSearchPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *BioSearchPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
