// Code generated by qtc from "bioSearch.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type BioSearchPage struct {
	BasePage
}

func (p *BioSearchPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<div>

    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Search query (user ID/system ID/system member ID" aria-label="Search query" aria-describedby="basic-addon2">
        <span class="input-group-text" id="basic-addon2"><button type="button" class="btn btn-primary">Search</button></span>
    </div>

    <p>lolololol</p>
</div>
`)
}

func (p *BioSearchPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *BioSearchPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
