name: Build and publish Docker image

on:
  release:
    types: [published]

env:
  IMAGE_NAME: lgballtdiscordbot

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Get tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Run Mage
        uses: magefile/mage-action@v1
        env:
          REGISTRY_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${GITHUB_REF/refs\/tags\//}
        with:
          version: latest
          args: -v setBuildVersion ${{ steps.get_version.outputs.VERSION }} docker:build docker:login ghcr.io codemicro docker:publish "ghcr.io/${{ github.repository }}/%s:latest"
      -
        name: Wait 10 seconds
        run: sleep 10
      -
        name: Notify Watchtower
        run: "curl -H \"Authorization: Bearer ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}\" localhost:8080/v1/update"
